Issue #35: satelite projects should use latest checkstyle as soon at …
sevntu-checkstyle/checkstyle-samples pull request #36
Opened 2022-08-19 09:47 UTC by Rahulkhinchi03

Fixes #35

2022-08-19 09:55 UTC, Rahulkhinchi03 commented
![Screenshot from 2022-08-19 15-18-44](https://user-images.githubusercontent.com/71710042/185594159-6e530949-2308-41e4-a7b8-d971024b3f2d.png)

2022-08-19 09:56 UTC, Rahulkhinchi03 commented
The problem, I am facing: Extra Whitespace occurs at two other lines!

![185594159-6e530949-2308-41e4-a7b8-d971024b3f2d](https://user-images.githubusercontent.com/71710042/185594411-1ebb56b1-9f76-4723-b1d6-ba34292d0129.png)

2022-08-19 12:49 UTC, romani requested changes
Items

2022-08-19 12:49 UTC, romani commented on .ci/update-project-version.sh
> +echo "Skipped Update, Version is latest"
+2 spaces

2022-08-19 13:32 UTC, Rahulkhinchi03 commented on .ci/update-project-version.sh
> +echo "Skipped Update, Version is latest"
Changes done in all other issues too!

2022-08-20 23:35 UTC, romani requested changes
item:

2022-08-20 23:35 UTC, romani commented on .ci/bump-ant-project-version.sh
> +set -e
apply comments from https://github.com/checkstyle/contribution/pull/635#pullrequestreview-1079599409

2022-08-20 23:45 UTC, romani commented
> I am facing: Extra Whitespace occurs at two other lines!

I am ok to merge extra spaces, if this is only extra stuff required, and next executions will not add more.

2022-08-21 15:18 UTC, Rahulkhinchi03 commented on .ci/bump-ant-project-version.sh
> +set -e
Changes Done

2022-08-27 13:35 UTC, romani commented
I fixed file to be in good form.

@Rahulkhinchi03 , please review changes and keep doing like I did.

2022-08-27 13:35 UTC, merged