Issue #35: satelite projects should use latest checkstyle as soon at is appears in maven repo
sevntu-checkstyle/checkstyle-samples pull request #38
Opened 2022-08-19 12:32 UTC by Rahulkhinchi03

Partially Fixes #35

2022-08-20 23:31 UTC, romani requested changes
items:

2022-08-20 23:31 UTC, romani commented on .ci/bump-gradle-version.sh
> +set -e
apply changes from https://github.com/checkstyle/contribution/pull/635#pullrequestreview-1079599409

2022-08-21 15:31 UTC, Rahulkhinchi03 commented on .ci/bump-gradle-version.sh
> +set -e
Changes Done

2022-08-27 14:02 UTC, romani approved these changes
fixed, tested

2022-08-27 14:02 UTC, merged